name: MSBuild

on: [push, pull_request]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app
      run: msbuild -t:rebuild -property:Configuration=Release
